### ISSUE TITLE
Sintesis de getión de proyectos de software

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/actividad-3-sintesis-IsraelNicolas61#2]
[Sintesis_IsraelNicolásPérez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-IsraelNicolas61/files/9463885/Sintesis_IsraelNicolasPerez.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
Calificacion 20
